### ISSUE TITLE
camel-case is a dev dependency

### ISSUE THREAD

**Issue by wolfgang42** [mulesoft-labs/raml-javascript-generator#5]
If you `npm install raml-javascript-generator` and try to use it you get the following traceback:
```
module.js:338
    throw err;
          ^
Error: Cannot find module 'camel-case'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Users\wfaust\Desktop\Development_git\specs\node_modules\raml-javascript-generator\lib\helpers\request-snippet.js:1:79)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

This is because the fix for #4 did not add `camel-case` to the dependencies in package.json.

**Comment by blakeembrey** [comment]
Thanks for the report and sorry for that :+1: I didn't catch it in the tests as it was already a `devDependency`. I've moved it across and published with `0.1.2` now.
